Y rest 33 child age range
ChristianRekfild/YourRest pull request #103
Opened 2023-10-23 16:04 UTC by MKSharpDev

2023-10-23 17:34 UTC, liliaretsia approved these changes

2023-10-23 20:24 UTC, YaroslavGritsishin commented on YourRest.WebApi.Tests/Controllers/AgeRangeControllerTest.cs
> +            Assert.Equal(HttpStatusCode.BadRequest, response.StatusCode);
Было бы не плохо проверить почему пришел BadRequest, если не проходит валидация данных необходимо получить объект с ошибками и обработать его. 
Пример получения объекта: 
```
if( response.StatusCode == HttpStatusCode.BadRequest)
{
   Assert.Equal(HttpStatusCode.BadRequest, response.StatusCode);

   var errorData= response.Content.ReadFromJsonAsync<ErrorViewModel>(); 

   Assert.Equal("'Street' должно быть заполнено.", errorData?.ValidationErrors[nameof(addressDto.Street)][0])
}
```
Пояснение:
**ValidationErrors это Dictionary<string, string[]>** по этому по ключу "**street**" ( ValidationErrors["street"] ) получим **массив**, так как на одно поле может быть много валидаторов (null, greterThen и.т.д) если нужен доступ  к первому сообщению обращаемся по индексу массива [0], ко второму [1].
**nameof(addressDto.Street)** было взято чтобы не промахнуться с названием поля к которому применяются ограничения по валидации.

2023-10-23 21:53 UTC, TarantasGitHub requested changes

2023-10-23 21:53 UTC, TarantasGitHub commented on YourRest.Application/UseCases/AgeRangeUseCases/CreateAgeRangeUseCase.cs
> +            await _ageRangeRepository.SaveChangesAsync();
Вроде по умолчанию он и так внутри SaveChanges вызывается. Второй раз нет необходимости

2023-10-23 21:53 UTC, TarantasGitHub commented on YourRest.Application/UseCases/AgeRangeUseCases/EditAgeRangeUseCase.cs
> +            await _ageRangeRepository.UpdateAsync(ageRangeUpdate);
Две лишние пустые строки

2023-10-23 21:53 UTC, TarantasGitHub commented on YourRest.Application/Interfaces/Age/IEditAgeRangeUseCase.cs
> +
Лишняя пустая строка

2023-10-23 21:53 UTC, TarantasGitHub commented on YourRest.Application/Dto/Validators/AgeRangeDtoValidator.cs
> +
Лишняя пустая строка

2023-10-23 21:53 UTC, TarantasGitHub commented on YourRest.Domain/Entities/AgeRange.cs
> +
Лишняя пустая строка

2023-10-23 21:53 UTC, TarantasGitHub commented on YourRest.WebApi.Tests/Controllers/AgeRangeControllerTest.cs
> +
Лишние пустые строки

2023-10-23 21:53 UTC, TarantasGitHub commented on YourRest.WebApi.Tests/Controllers/AgeRangeControllerTest.cs
> +
Лишние пустые строки

2023-10-23 21:53 UTC, TarantasGitHub commented on YourRest.WebApi.Tests/Controllers/AgeRangeControllerTest.cs
> +
Лишняя пустая строка

2023-10-23 21:53 UTC, TarantasGitHub commented on YourRest.WebApi.Tests/Controllers/AgeRangeControllerTest.cs
> +
Лишние пустые строки

2023-10-23 21:53 UTC, TarantasGitHub commented on YourRest.WebApi/Controllers/AgeRangeController.cs
> +
Лишняя пустая строка

2023-10-23 21:53 UTC, TarantasGitHub commented on YourRest.WebApi/Controllers/AgeRangeController.cs
> +
Лишняя пустая строка

2023-10-23 21:53 UTC, TarantasGitHub commented on YourRest.WebApi/Controllers/AgeRangeController.cs
> +
Лишние пустые строки

2023-10-25 13:14 UTC, TarantasGitHub requested changes

2023-10-25 13:14 UTC, TarantasGitHub commented on YourRest.Application/UseCases/AgeRangeUseCases/CreateAgeRangeUseCase.cs
> +        public async Task<AgeRangeWithIdDto> ExecuteAsync(AgeRangeDto ageRangeDto)
Если метод асинхронный хорошо бы в него передавать CancellationToken

2023-10-25 13:14 UTC, TarantasGitHub commented on YourRest.Application/UseCases/AgeRangeUseCases/EditAgeRangeUseCase.cs
> +        public async Task ExecuteAsync(AgeRangeWithIdDto ageRangeWithIdDto)
Если метод асинхронный хорошо бы в него передавать CancellationToken

2023-10-25 13:14 UTC, TarantasGitHub commented on YourRest.Application/UseCases/AgeRangeUseCases/GetAgeRangeByIdUseCase.cs
> +        public async Task<AgeRangeWithIdDto> ExecuteAsync(int ageRangeId)
Если метод асинхронный хорошо бы в него передавать CancellationToken

2023-10-25 20:16 UTC, TarantasGitHub requested changes

2023-10-25 20:16 UTC, TarantasGitHub commented on YourRest.Application/Interfaces/Age/ICreateAgeRangeUseCase.cs
> +        Task<AgeRangeWithIdDto> ExecuteAsync(AgeRangeDto ageRangeDto, CancellationToken token);
Для cancellationtoken можно добавить token = default чтобы ничего не поломалось

2023-10-25 20:16 UTC, TarantasGitHub commented on YourRest.Application/Interfaces/Age/IEditAgeRangeUseCase.cs
> +        Task ExecuteAsync(AgeRangeWithIdDto ageRangeWithIdDto, CancellationToken token);
token = default можно добавить

2023-10-25 20:16 UTC, TarantasGitHub commented on YourRest.Application/Interfaces/Age/IGetAgeRangeByIdUseCase.cs
> +        Task<AgeRangeWithIdDto> ExecuteAsync(int id, CancellationToken token);
token = default можно добавить

2023-10-25 20:16 UTC, TarantasGitHub commented on YourRest.Application/UseCases/AgeRangeUseCases/CreateAgeRangeUseCase.cs
> +        public async Task<AgeRangeWithIdDto> ExecuteAsync(AgeRangeDto ageRangeDto, CancellationToken token)
token = default можно добавить

2023-10-25 20:16 UTC, TarantasGitHub commented on YourRest.Application/UseCases/AgeRangeUseCases/CreateAgeRangeUseCase.cs
> +            var savedAgeRange = await _ageRangeRepository.AddAsync(ageRange);
вот сюда нужно передавать cancellationtoken

2023-10-25 20:16 UTC, TarantasGitHub commented on YourRest.Application/UseCases/AgeRangeUseCases/EditAgeRangeUseCase.cs
> +        public async Task ExecuteAsync(AgeRangeWithIdDto ageRangeWithIdDto, CancellationToken token)
= default

2023-10-25 20:16 UTC, TarantasGitHub commented on YourRest.Application/UseCases/AgeRangeUseCases/EditAgeRangeUseCase.cs
> +            var ageRange = await _ageRangeRepository.GetAsync(ageRangeWithIdDto.Id);
вот сюда передать token как параметр

2023-10-25 20:16 UTC, TarantasGitHub commented on YourRest.Application/UseCases/AgeRangeUseCases/GetAgeRangeByIdUseCase.cs
> +        public async Task<AgeRangeWithIdDto> ExecuteAsync(int ageRangeId, CancellationToken token)
= default

2023-10-25 20:16 UTC, TarantasGitHub commented on YourRest.Application/UseCases/AgeRangeUseCases/GetAgeRangeByIdUseCase.cs
> +            var ageRange = await ageRangeRepository.GetAsync(ageRangeId);
сюда вторым параметром token

2023-10-25 20:16 UTC, TarantasGitHub commented on YourRest.WebApi/Controllers/AgeRangeController.cs
> +        private CancellationToken token = new CancellationToken ();
Это неправильно, убрать

2023-10-25 20:16 UTC, TarantasGitHub commented on YourRest.WebApi/Controllers/AgeRangeController.cs
> +            var ageRangeResponse = await _getAgeRangeByIdUseCase.ExecuteAsync(id, token);
Вместо token использовать HttpContext.RequestAbprted

2023-10-25 20:16 UTC, TarantasGitHub commented on YourRest.WebApi/Controllers/AgeRangeController.cs
> +            var createdRoom = await _createAgeRangeUseCase.ExecuteAsync(ageRangeDto, token);
Вместо token использовать HttpContext.RequestAbprted

2023-10-25 20:16 UTC, TarantasGitHub commented on YourRest.WebApi/Controllers/AgeRangeController.cs
> +            await _editAgeRangeUseCase.ExecuteAsync(ageRangeWithId, token);
Вместо token использовать HttpContext.RequestAbprted

2023-10-25 22:36 UTC, MKSharpDev commented on YourRest.WebApi/Controllers/AgeRangeController.cs
> +
Исправлено

2023-10-25 22:37 UTC, MKSharpDev commented on YourRest.WebApi.Tests/Controllers/AgeRangeControllerTest.cs
> +            Assert.Equal(HttpStatusCode.BadRequest, response.StatusCode);
Добавлено
           var errorData = response.Content.ReadFromJsonAsync<ErrorViewModel>();
            var errorDescription = errorData?.Result?.ValidationErrors["AgeTo"].FirstOrDefault();

            Assert.Equal($"'Age To' должно быть больше или равно '{ageRange.AgeFrom}'.", errorDescription);

2023-10-25 22:37 UTC, MKSharpDev commented on YourRest.Application/UseCases/AgeRangeUseCases/CreateAgeRangeUseCase.cs
> +            await _ageRangeRepository.SaveChangesAsync();
Исправлено

2023-10-25 22:38 UTC, MKSharpDev commented on YourRest.Application/UseCases/AgeRangeUseCases/EditAgeRangeUseCase.cs
> +            await _ageRangeRepository.UpdateAsync(ageRangeUpdate);
Исправлено

2023-10-25 22:38 UTC, MKSharpDev commented on YourRest.Application/Interfaces/Age/IEditAgeRangeUseCase.cs
> +
Исправлено

2023-10-25 22:38 UTC, MKSharpDev commented on YourRest.Application/Dto/Validators/AgeRangeDtoValidator.cs
> +
Исправлено

2023-10-25 22:38 UTC, MKSharpDev commented on YourRest.WebApi.Tests/Controllers/AgeRangeControllerTest.cs
> +
Исправлено

2023-10-25 22:38 UTC, MKSharpDev commented on YourRest.WebApi.Tests/Controllers/AgeRangeControllerTest.cs
> +
Исправлено

2023-10-25 22:38 UTC, MKSharpDev commented on YourRest.WebApi/Controllers/AgeRangeController.cs
> +
Исправлено

2023-10-25 22:38 UTC, MKSharpDev commented on YourRest.WebApi/Controllers/AgeRangeController.cs
> +
Исправлено

2023-10-25 22:38 UTC, MKSharpDev commented on YourRest.WebApi/Controllers/AgeRangeController.cs
> +
Исправлено

2023-10-25 22:38 UTC, MKSharpDev commented on YourRest.Application/UseCases/AgeRangeUseCases/CreateAgeRangeUseCase.cs
> +        public async Task<AgeRangeWithIdDto> ExecuteAsync(AgeRangeDto ageRangeDto)
Исправлено

2023-10-25 22:39 UTC, MKSharpDev commented on YourRest.Application/UseCases/AgeRangeUseCases/EditAgeRangeUseCase.cs
> +        public async Task ExecuteAsync(AgeRangeWithIdDto ageRangeWithIdDto)
Исправлено

2023-10-25 22:39 UTC, MKSharpDev commented on YourRest.Application/UseCases/AgeRangeUseCases/GetAgeRangeByIdUseCase.cs
> +        public async Task<AgeRangeWithIdDto> ExecuteAsync(int ageRangeId)
Исправлено

2023-10-25 22:39 UTC, MKSharpDev commented on YourRest.Application/Interfaces/Age/ICreateAgeRangeUseCase.cs
> +        Task<AgeRangeWithIdDto> ExecuteAsync(AgeRangeDto ageRangeDto, CancellationToken token);
Исправлено

2023-10-25 22:39 UTC, MKSharpDev commented on YourRest.Application/Interfaces/Age/IEditAgeRangeUseCase.cs
> +        Task ExecuteAsync(AgeRangeWithIdDto ageRangeWithIdDto, CancellationToken token);
Исправлено

2023-10-25 22:39 UTC, MKSharpDev commented on YourRest.Application/Interfaces/Age/IGetAgeRangeByIdUseCase.cs
> +        Task<AgeRangeWithIdDto> ExecuteAsync(int id, CancellationToken token);
Исправлено

2023-10-25 22:39 UTC, MKSharpDev commented on YourRest.Application/UseCases/AgeRangeUseCases/CreateAgeRangeUseCase.cs
> +        public async Task<AgeRangeWithIdDto> ExecuteAsync(AgeRangeDto ageRangeDto, CancellationToken token)
Исправлено

2023-10-25 22:41 UTC, MKSharpDev commented on YourRest.Application/UseCases/AgeRangeUseCases/CreateAgeRangeUseCase.cs
> +            var savedAgeRange = await _ageRangeRepository.AddAsync(ageRange);
Изменено на 
var savedAgeRange = await _ageRangeRepository.AddAsync(ageRange , true,  token);

2023-10-25 22:42 UTC, MKSharpDev commented on YourRest.Application/UseCases/AgeRangeUseCases/GetAgeRangeByIdUseCase.cs
> +            var ageRange = await ageRangeRepository.GetAsync(ageRangeId);
Исправлено

2023-10-25 22:42 UTC, MKSharpDev commented on YourRest.WebApi/Controllers/AgeRangeController.cs
> +        private CancellationToken token = new CancellationToken ();
Исправлено

2023-10-25 22:42 UTC, MKSharpDev commented on YourRest.WebApi/Controllers/AgeRangeController.cs
> +            var ageRangeResponse = await _getAgeRangeByIdUseCase.ExecuteAsync(id, token);
Исправлено

2023-10-25 22:42 UTC, MKSharpDev commented on YourRest.WebApi/Controllers/AgeRangeController.cs
> +            var createdRoom = await _createAgeRangeUseCase.ExecuteAsync(ageRangeDto, token);
Исправлено

2023-10-25 22:42 UTC, MKSharpDev commented on YourRest.WebApi/Controllers/AgeRangeController.cs
> +            await _editAgeRangeUseCase.ExecuteAsync(ageRangeWithId, token);
Исправлено

2023-10-25 23:09 UTC, TarantasGitHub approved these changes

2023-10-26 07:15 UTC, merged