Your rest 81 Minio
ChristianRekfild/YourRest pull request #118
Opened 2023-11-13 17:04 UTC by liliaretsia

2023-11-19 13:22 UTC, MKSharpDev approved these changes

2023-11-19 21:23 UTC, TarantasGitHub requested changes

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.Application/Dto/Validators/PhotoDtoValidator.cs
> +        private const long MaxFileSize = 5 * 1024 * 1024; // 5 MB
Не мало ли 5 Мб для фото? Какой-нибудь вид из окна запросто будет больше весить

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.Application/Interfaces/Photo/IAccommodationPhotoUploadUseCase.cs
> +        Task<PhotoUploadResponseDto> Handle(PhotoUploadModel request, string bucketName);
Почему не ExecuteAsync?

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.Application/Interfaces/Photo/IRoomPhotoUploadUseCase.cs
> +        Task<PhotoUploadResponseDto> Handle(RoomPhotoUploadModel request, string bucketName);
Почему не ExecuteAsync?

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.Application/Services/FileService.cs
> +    public async Task<string> AddPhoto(FileData fileData, string bucketName)
Не хватает Async в названии метода

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.Application/Services/IFileService.cs
> +    Task<string> AddPhoto(FileData fileData, string bucketName);
Async

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.Application/UseCases/CreateAccommodationUseCase.cs
> +        public async Task<AccommodationDto> Execute(CreateAccommodationDto accommodationDto, CancellationToken cancellationToken)
Async в названии метода не хватает

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.Application/UseCases/CreateAccommodationUseCase.cs
> +            accommodation.Description = accommodationDto.Description;
Не лучше ли настроить маппинг полей? Чтобы трансформация автоматом происходила.

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.Application/UseCases/CreateAccommodationUseCase.cs
> +                Id = accommodationType.Id,
Mapping

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.Application/UseCases/CreateAccommodationUseCase.cs
> +            {
Mapping

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.Application/UseCases/FetchAccommodationsUseCase.cs
> +        public async Task<IEnumerable<AccommodationExtendedDto>> Execute(FetchAccommodationsViewModel viewModel)
Async в названии метода не хватает

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.Application/UseCases/FetchAccommodationsUseCase.cs
> +            return new AccommodationExtendedDto
Mapping

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.Application/UseCases/GetAccommodationTypeListUseCase .cs
> +        public async Task<IEnumerable<AccommodationTypeDto>> Execute()
Async в названии метода не хватает и CancellationTocen в параметрах

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.Application/UseCases/GetAccommodationTypeListUseCase .cs
> +            var accommodationTypes = await _accommodationTypeRepository.GetAllAsync();
Прокинуть сюда CancellationToken когда он будет в параметрах метода

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.Application/UseCases/Photo/AccommodationPhotoUploadUseCase.cs
> +        public async Task<PhotoUploadResponseDto> Handle(PhotoUploadModel photoUploadModel, string bucketName)
Почему не ExecuteAsync и где CancellationToken?

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.Application/UseCases/Photo/AccommodationPhotoUploadUseCase.cs
> +            var accommodation = await _accommodationRepository.GetAsync(photoUploadModel.AccommodationId);
Token

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.Application/UseCases/Photo/AccommodationPhotoUploadUseCase.cs
> +            var photoPath = await _fileService.AddPhoto(fileData, bucketName);
Async + token

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.Application/UseCases/Photo/AccommodationPhotoUploadUseCase.cs
> +            var photo = new AccommodationPhoto()
Mapping

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.Application/UseCases/Photo/AccommodationPhotoUploadUseCase.cs
> +            var savedPhoto = await _photoRepository.AddAsync(photo, false);
token

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.Application/UseCases/Photo/AccommodationPhotoUploadUseCase.cs
> +            await _photoRepository.SaveChangesAsync();
Смысл при вызове _photoRepository.AddAsync передавать false для отмены SaveChanges  и потом сразу его вызывать?

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.Application/UseCases/Photo/RoomPhotoUploadUseCase.cs
> +        public async Task<PhotoUploadResponseDto> Handle(RoomPhotoUploadModel request, string bucketName)
Почему не ExecuteAsync и почему без CancellationToken?

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.Application/UseCases/Photo/RoomPhotoUploadUseCase.cs
> +            var room = await _roomRepository.GetAsync(request.RoomId);
Token

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.Application/UseCases/Photo/RoomPhotoUploadUseCase.cs
> +            var photoPath = await _fileService.AddPhoto(fileData, bucketName);
Async  и token

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.Application/UseCases/Photo/RoomPhotoUploadUseCase.cs
> +            var photo = new RoomPhoto()
Mapping

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.Application/UseCases/Photo/RoomPhotoUploadUseCase.cs
> +            var savedPhoto = await _photoRepository.AddAsync(photo, false);
Опять нет Token и отмена SaveChanges с последующим вызовом SaveChanges. Зачем?

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.Domain/Repositories/IAccommodationPhotoRepository.cs
> +
Лишняя строка

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.Domain/Repositories/IRoomPhotoRepository.cs
> +
Лишняя строка

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.WebApi/Controllers/AccommodationController.cs
>              var hotels = await _fetchAccommodationsUseCase.Execute(fetchHotelsViewModel);
Async + token

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.WebApi/Controllers/AccommodationController.cs
> +            var createdAccommodation = await _createAccommodationUseCase.Execute(accommodationExtendedDto, HttpContext.RequestAborted);
Async у названия метода

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.WebApi/Controllers/AccommodationTypeController.cs
> +            IEnumerable<AccommodationTypeDto> types = await _getAccommodationTypeListUseCase.Execute();
Async + token

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.WebApi/Controllers/PhotoController.cs
> +            var dto = await _accommodationPhotoUploadUseCase.Handle(model, _awsOptions.BucketName);
ExecuteAsync + token

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.WebApi/Controllers/PhotoController.cs
> +            var dto = await _roomPhotoUploadUseCase.Handle(model, _awsOptions.BucketName);
ExecuteAsync + token

2023-11-19 21:23 UTC, TarantasGitHub commented on YourRest.WebApi/Controllers/PhotoController.cs
> +            var fileDto = await _fileService.GetFileByPathAsync(path, _awsOptions.BucketName);
Token

2023-11-28 08:18 UTC, liliaretsia commented on YourRest.WebApi/Controllers/PhotoController.cs
> +            var fileDto = await _fileService.GetFileByPathAsync(path, _awsOptions.BucketName);
Добавила везде Token

2023-11-28 08:19 UTC, liliaretsia reviewed
Добавила токен и Async в названия

2023-11-30 19:12 UTC, TarantasGitHub requested changes

2023-12-05 09:38 UTC, TarantasGitHub approved these changes

2023-12-05 20:47 UTC, merged