Your rest 87 add booking new
ChristianRekfild/YourRest pull request #120
Opened 2023-11-15 11:34 UTC by MKSharpDev

2023-11-19 20:58 UTC, TarantasGitHub requested changes

2023-11-19 20:58 UTC, TarantasGitHub commented on Infrastructure/YourRest.Infrastructure.Core/Repositories/PgRepository.cs
> +        public async Task<IEnumerable<T>> FindAsyncDoubleWhere(Expression<Func<T, bool>> expressionFirst, Expression<Func<T, bool>> expression, CancellationToken cancellationToken = default)
Не могу придумать где бы это было нужно

2023-11-19 20:58 UTC, TarantasGitHub commented on YourRest.Application/UseCases/HotelBookingUseCase/CreateHotelBookingUseCase.cs
> +                var tempRoom = await roomRepository.GetAsync(roomId);
Вот тут можно за один запрос к базе получить все комнаты, указанные в бронировании. А потом проверить чтобы все были и ничего не было пропущенно. Это будет более эффективно с точки зрения использования ресурсов. Так как оброщение к базе дорогая операция.

2023-11-19 20:58 UTC, TarantasGitHub commented on YourRest.Application/UseCases/HotelBookingUseCase/CreateHotelBookingUseCase.cs
> +                //    FindAsyncDoubleWhere(t => t.Rooms.Contains(room), x => (x.StartDate <= bookingDto.StartDate && bookingDto.EndDate < x.StartDate) ||
Если чудо метод FindAsyncDoubleWhere больше не используется - его нужно удалить. И на будущее, метод должен был бы называться FindDoubleWhereAsync

2023-11-19 20:58 UTC, TarantasGitHub commented on YourRest.Application/UseCases/HotelBookingUseCase/CreateHotelBookingUseCase.cs
> +                    throw new InvalidParameterException("Бронируемой комнаты не существует.");
Первый сценарий для UnitTest когда Mock репозиторий не возвращает комнату

2023-11-19 20:58 UTC, TarantasGitHub commented on YourRest.Application/UseCases/HotelBookingUseCase/CreateHotelBookingUseCase.cs
> +                throw new InvalidParameterException("Пустая бронь - в брони нет комнат");
По идее сюда не получится добраться не получив исключительной ситуации по поводу отсутствия бронируемой комнаты. Для проверки наличия в принципе комнаты для брони - лучше проверять входящие параметры до обращения к базе

2023-11-19 20:58 UTC, TarantasGitHub commented on YourRest.Application/UseCases/HotelBookingUseCase/CreateHotelBookingUseCase.cs
> +
Лишние строки

2023-11-19 20:58 UTC, TarantasGitHub commented on YourRest.Application/UseCases/HotelBookingUseCase/CreateHotelBookingUseCase.cs
> +            }
И это второй сценарий для UnitTest

2023-11-19 20:58 UTC, TarantasGitHub commented on YourRest.Application/UseCases/HotelBookingUseCase/CreateHotelBookingUseCase.cs
> +                    throw new InvalidParameterException("Бронирование на выбранные даты невозможно. Комната занята.");
Третий сценарий для UnitTest

2023-11-19 20:58 UTC, TarantasGitHub commented on YourRest.Domain/Entities/Booking.cs
> +        public Booking() => Rooms = new List<Room>();
Конструктор лучше после объявлени свойств располагать. Чтобы однотипно было.

2023-11-19 20:58 UTC, TarantasGitHub commented on YourRest.Domain/Repositories/IRepository.cs
> +        Task<IEnumerable<T>> FindAsyncDoubleWhere(Expression<Func<T, bool>> expressionFirst, Expression<Func<T, bool>> expression, CancellationToken cancellationToken = default);
Убрать, если не используется

2023-11-20 09:51 UTC, MKSharpDev commented on Infrastructure/YourRest.Infrastructure.Core/Repositories/PgRepository.cs
> +        public async Task<IEnumerable<T>> FindAsyncDoubleWhere(Expression<Func<T, bool>> expressionFirst, Expression<Func<T, bool>> expression, CancellationToken cancellationToken = default)
Удалил

2023-11-20 09:51 UTC, MKSharpDev commented on YourRest.Application/UseCases/HotelBookingUseCase/CreateHotelBookingUseCase.cs
> +                //    FindAsyncDoubleWhere(t => t.Rooms.Contains(room), x => (x.StartDate <= bookingDto.StartDate && bookingDto.EndDate < x.StartDate) ||
Удалил

2023-11-20 09:53 UTC, MKSharpDev commented on YourRest.Application/UseCases/HotelBookingUseCase/CreateHotelBookingUseCase.cs
> +                    throw new InvalidParameterException("Бронируемой комнаты не существует.");
Добавил

2023-11-20 09:55 UTC, MKSharpDev commented on YourRest.Domain/Entities/Booking.cs
> +        public Booking() => Rooms = new List<Room>();
Перетянул + сделал так же в Accomodation

2023-11-20 13:37 UTC, TarantasGitHub requested changes

2023-11-20 13:37 UTC, TarantasGitHub commented on YourRest.Application/Dto/Mappers/Profiles/BookingDtoProfile.cs
> +    public class BookingDtoProfile : Profile
Зачем в проекте класс в котором всё закомментировано?

2023-11-20 13:37 UTC, TarantasGitHub commented on YourRest.Application/Dto/Validators/BookingDtoValidator.cs
> +
Зачем лишние пустые строки?

2023-11-20 13:37 UTC, TarantasGitHub commented on YourRest.Application/UseCases/HotelBookingUseCase/CreateHotelBookingUseCase.cs
> +                var alreadyHaveBooking = await bookingRepository.
Странное форматирование как метода там и параметров. Не сразу понятно что к чему относится

2023-11-20 17:26 UTC, MKSharpDev commented on YourRest.Application/UseCases/HotelBookingUseCase/CreateHotelBookingUseCase.cs
> +                var alreadyHaveBooking = await bookingRepository.
Подвинул

2023-11-20 17:26 UTC, MKSharpDev commented on YourRest.Application/Dto/Validators/BookingDtoValidator.cs
> +
Убрал

2023-11-20 17:26 UTC, MKSharpDev commented on YourRest.Application/Dto/Mappers/Profiles/BookingDtoProfile.cs
> +    public class BookingDtoProfile : Profile
Что б при желании его быстро реализовать, если понадобится. Да и писал его не я и удалять не особо хочется. А закоментил когда разбирался с сущностями и убирал Guest. 
Исправил - закоментил весь класс

2023-11-20 18:48 UTC, YaroslavGritsishin approved these changes

2023-11-22 16:42 UTC, merged