Fluent validation
ChristianRekfild/YourRest pull request #96
Opened 2023-10-16 22:43 UTC by YaroslavGritsishin

Предлагаю внедрить в проект библиотеку по валидации данных "FluentValidation".

2023-10-18 13:17 UTC, TarantasGitHub requested changes

2023-10-18 13:17 UTC, TarantasGitHub commented on Infrastructure/YourRest.Producer.Infrastructure/Migrations/20231012214239_Room_And_RoomFacilities.cs
> +                    RoomId = table.Column<int>(type: "integer", nullable: false)
Связь разве один ко многим?

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.Application/Dto/ViewModels/RoomFacilityViewModel.cs
> +
Лишняя строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.Application/UseCases/Facility/AddRoomFacilityUseCase.cs
> +        }
Не хватает разделительной строки

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.Application/UseCases/Facility/EditRoomFacilityUseCase.cs
> +        }
Не хватает разделительной строки

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.Application/UseCases/Facility/GetRoomFacilitiesByRoomIdUseCase.cs
> +        private readonly IRoomRepository roomRepository;
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.Application/UseCases/Facility/GetRoomFacilityByIdUseCase.cs
> +        }
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.Application/UseCases/Facility/RemoveRoomFacilityUseCase.cs
> +        }
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.Application/UseCases/Room/EditRoomUseCase.cs
> +        private readonly IRoomRepository roomRepository;
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.Application/UseCases/Room/EditRoomUseCase.cs
> +        }
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.Application/UseCases/Room/GetRoomByIdUseCase.cs
> +        private readonly IRoomRepository roomRepository;
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.Application/UseCases/Room/GetRoomByIdUseCase.cs
> +        }
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.Application/UseCases/Room/RemoveRoomUseCase.cs
> +        private readonly IRoomRepository roomRepository;
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.Application/UseCases/Room/RemoveRoomUseCase.cs
> +        }
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.Domain/Entities/RoomFacility.cs
> +
Лишняя строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.WebApi.Tests/Controllers/CitiesControllerTest.cs
> +    public class CitiesControllerTest : IClassFixture<SingletonApiTest>
Либо [Collection(...)] либо : IClassFixture<...>

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.WebApi.Tests/Controllers/CitiesControllerTest.cs
> +            var response = await fixture.Client.GetAsync($"/api/cities?regionId=200");
Странное условие regionId=200 в строке запроса

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.WebApi.Tests/Controllers/RoomFacilityControllerTest.cs
> +        private int RoomId { get; set; }
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.WebApi.Tests/Controllers/RoomFacilityControllerTest.cs
> +        }
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.WebApi.Tests/Controllers/RoomFacilityControllerTest.cs
> +        }
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.WebApi.Tests/Controllers/RoomFacilityControllerTest.cs
> +        }
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.WebApi.Tests/Controllers/RoomFacilityControllerTest.cs
> +        }
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.WebApi.Tests/Controllers/RoomTypeControllerTest.cs
> +        private readonly SingletonApiTest fixture;
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.WebApi.Tests/UnitTests/AddressDtoValidationTests.cs
> +        private readonly AddressDtoValidator addressValidator;
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.WebApi.Tests/UnitTests/AddressDtoValidationTests.cs
> +        }
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.WebApi.Tests/UnitTests/RoomFacilityViewModelValidationsTests.cs
> +        private readonly RoomFacilityViewModelValidator roomFacilityValidator;
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.WebApi.Tests/UnitTests/RoomFacilityViewModelValidationsTests.cs
> +        }
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.WebApi.Tests/UnitTests/RoomFacilityViewModelValidationsTests.cs
> +        }
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.WebApi.Tests/UnitTests/RoomViewModelValidationsTests.cs
> +        private RoomViewModelValidator roomValidator;
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.WebApi.Tests/UnitTests/RoomViewModelValidationsTests.cs
> +        }
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.WebApi.Tests/UnitTests/RoomViewModelValidationsTests.cs
> +        }
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.WebApi.Tests/UnitTests/RoomViewModelValidationsTests.cs
> +        }
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.WebApi.Tests/UnitTests/RoomViewModelValidationsTests.cs
> +        }
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.WebApi.Tests/UnitTests/RoomViewModelValidationsTests.cs
> +        }
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.WebApi.Tests/UnitTests/RoomViewModelValidationsTests.cs
> +        }
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.WebApi/Controllers/RoomController.cs
> +        }
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.WebApi/Controllers/RoomController.cs
> +        }
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.WebApi/Controllers/RoomController.cs
> +        }
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.WebApi/Controllers/RoomController.cs
> +        }
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.WebApi/Controllers/RoomFacilityController.cs
> +        }
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.WebApi/Controllers/RoomFacilityController.cs
> +        }
Разделительная строка

2023-10-18 13:17 UTC, TarantasGitHub commented on YourRest.WebApi/Controllers/RoomFacilityController.cs
> +        }
Разделительная строка

2023-10-18 20:05 UTC, liliaretsia approved these changes

2023-10-19 12:07 UTC, YaroslavGritsishin commented on Infrastructure/YourRest.Producer.Infrastructure/Migrations/20231012214239_Room_And_RoomFacilities.cs
> +                    RoomId = table.Column<int>(type: "integer", nullable: false)
Временно было так исправлю на многие ко многим в рамках другой задачи.

2023-10-19 12:08 UTC, YaroslavGritsishin commented on YourRest.Application/UseCases/Facility/AddRoomFacilityUseCase.cs
> +        }
Зачем разделительная строка в конструкторе во время инициализации поля?

2023-10-19 12:09 UTC, YaroslavGritsishin commented on YourRest.Application/UseCases/Facility/EditRoomFacilityUseCase.cs
> +        }
А что тут необходимо разделить, одна строка в конструкторе.

2023-10-19 14:33 UTC, TarantasGitHub approved these changes

2023-10-19 14:46 UTC, MKSharpDev approved these changes

2023-10-19 15:51 UTC, merged

2023-10-19 16:31 UTC, ChristianRekfild approved these changes